# Prometheus configuration for monitoring AI Medical Disease Detection System
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "medical_ai_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Medical AI Application
  - job_name: 'medical-ai-app'
    static_configs:
      - targets: ['medical-ai-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s

  # FastAPI metrics
  - job_name: 'fastapi'
    static_configs:
      - targets: ['medical-ai-app:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Streamlit metrics (if available)
  - job_name: 'streamlit'
    static_configs:
      - targets: ['medical-ai-app:8501']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Docker metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # Nginx metrics
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']

  # Grafana metrics
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
